language: node_js

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@'>=2.13.5'
  - npm install -g gulp

before_deploy:
  - gulp production

deploy:
  - provider: s3
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "enhancv.com"
    local_dir: cdn
    skip_cleanup: true
    on:
      repo: Enhancv/homepage
      branch: master

  - provider: s3
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "dev-home.enhancv.com"
    local_dir: cdn
    skip_cleanup: true
    on:
      repo: Enhancv/homepage
      branch: develop
