language: node_js
sudo: false
node_js:
  - "4.1"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g gulp
  - npm install -g http-server

before_script:
  - npm run lint
  - gulp build
  - cd build && http-server -a localhost --silent &
  - sleep 2

before_deploy:
  - gulp production
  - chmod 777 bin/deploy_s3.sh

after_deploy:
  - >
    curl -X POST \
        --data-urlencode "payload={
            \"channel\": \"#ci\",
            \"username\": \"webhookbot\",
            \"text\": \"$TRAVIS_BRANCH deployed\",
            \"icon_emoji\": \":shipit:\"
        }" \
        https://hooks.slack.com/services/T0294QTKB/B0PLXDQKT/$SLACK_SECRET

deploy:
  - provider: script
    script: AWSBUCKET="enhancv.com" bin/deploy_s3.sh
    skip_cleanup: true
    cache_control: "max-age=14400"
    on:
      repo: enhancv/homepage
      branch: master
      
  - provider: script
    script: AWSBUCKET="dev-home.enhancv.com" bin/deploy_s3.sh
    skip_cleanup: true
    on:
      repo: enhancv/homepage
      branch: develop
