language: node_js
node_js:
- 6.9.1
cache:
  pip: true
  directories:
  - node_modules
  - bower_components

install:
- npm install
- npm run bower
- pip install --user awscli
script:
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: BUCKET="dev-home.enhancv.com" bin/deploy.sh
    on:
      repo: enhancv/homepage
      branch: staging
  - provider: script
    skip_cleanup: true
    script: BUCKET="enhancv.com" bin/deploy.sh
    on:
      repo: enhancv/homepage
      branch: master
