language: node_js
sudo: false
node_js:
  - "4.1"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g gulp
  - npm install -g http-server

before_script:
  - npm run lint
  - gulp build
  - cd build && http-server -a localhost --silent &
  - sleep 2

before_deploy:
  - gulp production

after_deploy:
  - >
    curl -X POST \
        --data-urlencode "payload={
            \"channel\": \"#ci\",
            \"username\": \"webhookbot\",
            \"text\": \"$TRAVIS_BRANCH deployed\",
            \"icon_emoji\": \":shipit:\"
        }" \
        https://hooks.slack.com/services/T0294QTKB/B0PLXDQKT/$SLACK_SECRET

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "enhancv.com"
    local_dir: cdn
    acl: public_read
    skip_cleanup: true
    on:
      repo: enhancv/homepage
      branch: master

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "dev-home.enhancv.com"
    local_dir: cdn
    acl: public_read
    skip_cleanup: true
    expires:
      - "2020-01-01 00:00:00 -0000":
        - "**/*.png"
        - "**/*.jpg"
        - "**/*.gif"
        - "**/*.js"
        - "**/*.css"
        - "**/*.svg"
    cache_control:
      - max-age=2592000
      - no-cache:
        - **/*.html
    on:
      repo: enhancv/homepage
      branch: develop
